spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    social:
        facebook:
            appId: 487654301400466
            appSecret: 3ec76bf19fbfeaf187a6673d1cf16411
    jpa:
        generate-ddl: true
        show-sql: true
    h2:
        console:
            enabled: true
   
logging:
    level:
        com.millky.blog: DEBUG

server:
    error:
        whitelabel:
            enabled: false