spring:
    view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
    social:
        facebook:
            appId: 487654301400466
            appSecret: 
logging:
    level:
        com.millky.blog: DEBUG
