spring:
    view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
    social:
        facebook:
            appId: 487661008066462
            appSecret: 
logging:
    level:
        com.millky.blog: INFO
